# Site settings
title: Izoslav's blog
email: dev@izoslav.com
description: > # this means to ignore newlines until "baseurl:"
  Programming and video games enthusiast, mostly using C++ in day to day basis
  but not afraid to dabble in any other programming language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://izoslav.github.io" # the base hostname & protocol for your site
github_username:  Izoslav

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight